import test from 'node:test';import assert from 'node:assert/strict';
import {meetingTooltipHTML,attendanceComparison,attendanceTrendChart,comparisonHTML,historyRows,historyColumns,meetingHistoryTable} from '../dist/insight-evidence.js';
import {demoData} from '../dist/analytics.js';import {analyzeDataset} from '../dist/analytics/pipeline.js';import {importCSV} from '../dist/analytics/data-quality.js';
const rows=Array.from({length:6},(_,i)=>({id:String(i),date:`2026-09-0${i+1}`,attendance:i<3?30:15}));
test('chart keeps every meeting and sorts actual normalized dates',()=>{const html=attendanceTrendChart([...rows].reverse());assert.equal((html.match(/data-meeting-point=/g)||[]).length,6);assert.ok(html.indexOf('Sep 1, 2026')<html.indexOf('Sep 6, 2026'));assert.equal(rows[0].date,'2026-09-01')});
test('balanced comparison exposes dates, headcounts, sample size and percent',()=>{const c=attendanceComparison(rows);assert.equal(c.currentAverage,15);assert.equal(c.previousAverage,30);assert.equal(c.absoluteDifference,-15);assert.equal(c.percentDifference,-50);assert.equal(c.sampleSize,6);assert.deepEqual(c.currentPeriod,['2026-09-04','2026-09-05','2026-09-06']);assert.match(comparisonHTML(rows),/Last 3 meetings/);assert.match(comparisonHTML(rows),/Previous 3 meetings/)});
test('one and fewer than six meetings do not claim percentage trend',()=>{for(let n=1;n<6;n++){assert.equal(attendanceComparison(rows.slice(0,n)).available,false);assert.doesNotMatch(comparisonHTML(rows.slice(0,n)),/\d%/)}assert.match(comparisonHTML(rows.slice(0,1)),/Add another meeting/)});
test('zero baseline does not invent a percentage',()=>{assert.equal(attendanceComparison(rows.map((r,i)=>({...r,attendance:i<3?0:10}))).percentDifference,null)});
test('history includes all records on expansion and sorts newest first',()=>{const d=analyzeDataset(demoData()).rows;assert.equal(historyRows(d)[0].date,historyRows(d,true).at(-1).date);assert.equal((meetingHistoryTable(d,false,true).match(/<tr(?:\s[^>]*)?>/g)||[]).length,d.length+1);assert.match(meetingHistoryTable(d),/View all 28 meetings/)});
test('empty optional fields disappear while zero values remain',()=>{assert.deepEqual(historyColumns(rows).map(c=>c[0]),['date','attendance']);assert.ok(historyColumns([{...rows[0],new_members:0}]).some(c=>c[0]==='new_members'));assert.match(meetingHistoryTable([{...rows[0],notes:'<script>'+ 'x'.repeat(100)}]),/&lt;script&gt;/)});
test('demo and CSV uploads use the same chart and history with normalized dates',()=>{const uploaded=importCSV('Date,Attendance\n9/6/2026,15\n9/1/2026,30').rows;for(const d of [analyzeDataset(demoData()).rows,uploaded]){assert.equal((attendanceTrendChart(d).match(/data-meeting-point=/g)||[]).length,d.length);assert.equal((meetingHistoryTable(d,false,true).match(/<tr(?:\s[^>]*)?>/g)||[]).length,d.length+1)}});

test('compact tooltip exposes date, optional name and attendance for every demo point',()=>{for(const r of analyzeDataset(demoData()).rows){const html=meetingTooltipHTML(r);assert.ok(html.includes(String(r.attendance)+' <small>attendees'));assert.match(html,/2026/);assert.ok(html.includes(r.name));assert.doesNotMatch(html,/returning|new_members|special_event/)}const basic=meetingTooltipHTML({date:'2026-09-17',attendance:35});assert.match(basic,/Sep 17, 2026/);assert.doesNotMatch(basic,/tooltip-name/);assert.match(meetingTooltipHTML({date:'2026-09-17',attendance:0,name:'<img>'}),/&lt;img&gt;/)});
