import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeEntry,validEntries,updateEntry,deleteEntry,saveEntries,loadEntries,entryWarning,STORAGE_KEY} from '../dist/meeting-store.js';
import {importCSV} from '../dist/analytics/data-quality.js';import {analyzeDataset} from '../dist/analytics/pipeline.js';
import * as XLSX from '../dist/vendor/xlsx.mjs';import {parseWorkbook} from '../dist/importers.js';
const raw={id:'a',date:'2026-09-03',name:'Debate',attendance:'28',type:'Discussion',promotion:'Instagram + Posters'};
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)}};
test('direct creation and edit use canonical records and update analysis',()=>{const first=normalizeEntry(raw);assert.equal(first.attendance,28);assert.equal(first.reach,null);assert.deepEqual(first.channels,['Instagram','Posters']);const edited=updateEntry([first],'a',{attendance:'40'});assert.equal(analyzeDataset(validEntries(edited)).outputs.calculate_attendance_metrics.average,40);assert.equal(first.attendance,28);assert.equal(deleteEntry(edited,'a').length,0)});
test('invalid values are retained as drafts but cannot enter analysis',()=>{for(const patch of [{date:'2026-02-30'},{attendance:-1},{attendance:2.5},{reach:-1},{signups:-2},{days_promoted_before:-1},{new_members:-3}]){assert.throws(()=>normalizeEntry({...raw,...patch}));assert.deepEqual(validEntries([{...raw,...patch}]),[])}assert.equal(normalizeEntry({...raw,attendance:0}).attendance,0);assert.match(entryWarning({...raw,new_members:20,returning_members:12}),/greater/)});
test('persistence roundtrips edits and unfinished drafts without demo records',()=>{const storage=memory();const records=[normalizeEntry(raw),{id:'draft',date:'',attendance:''}];assert.equal(saveEntries(storage,records),null);assert.deepEqual(loadEntries(storage).records,records);assert.equal(validEntries(loadEntries(storage).records).length,1);saveEntries(storage,deleteEntry(records,'a'));assert.equal(loadEntries(storage).records.length,1);saveEntries(storage,[]);assert.deepEqual(loadEntries(storage).records,[])});
test('storage failures are reported rather than claiming saved',()=>{const blocked={getItem(){throw Error()},setItem(){throw Error()}};assert.match(loadEntries(blocked).error,/could not be read/);assert.match(saveEntries(blocked,[]),/Not saved/);const storage=memory();storage.setItem(STORAGE_KEY,'broken');assert.match(loadEntries(storage).error,/could not be read/);assert.equal(storage.getItem(STORAGE_KEY),'broken')});
test('manual CSV and Excel records share the same schema and metrics',()=>{const csv='Date,Meeting Name,Attendance,Meeting Type,Promotion Channels\n2026-09-03,Debate,28,Discussion,Instagram + Posters';const imported=importCSV(csv).rows[0];const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['Date','Meeting Name','Attendance','Meeting Type','Promotion Channels'],['2026-09-03','Debate',28,'Discussion','Instagram + Posters']]),'Meetings');const excel=parseWorkbook(XLSX.write(book,{type:'array',bookType:'xlsx'}),XLSX).rows[0];for(const record of [imported,excel]){assert.deepEqual({...record,id:'a'},normalizeEntry(raw));assert.equal(analyzeDataset([record]).outputs.calculate_attendance_metrics.average,28)}});


